version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      PUBLIC_API_BASE_URL: "http://server:8080"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/database"
      REDIS_URL: "redis://redis:6379"
      CLIENT_URL: "http://client:4173"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./server/database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
