//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub mod prelude;

pub mod account;
pub mod api;
pub mod app;
pub mod conversation;
pub mod conversation_account;
pub mod dto;
pub mod enquiry;
pub mod file;
pub mod message;
pub mod review;
pub mod sea_orm_active_enums;
